export const Path = {
    HOME: '/',
    AUTH: '/auth',
    MAIN: '/main',
    FEEDBACKS: '/feedbacks',
    CALENDAR: '/calendar',
    REGISTRATION: '/auth/registration',
    CONFIRM_EMAIL: '/auth/confirm-email',
    CHANGE_PASS: '/auth/change-password',
    RESULT: '/result',
    SUCCESS: '/result/success',
    ERROR_LOGIN: '/result/error-login',
    ERROR_USER_EXIST: '/result/error-user-exist',
    ERRR0R_CHEK_EMAIL_NO_EXIST: '/result/error-check-email-no-exist',
    ERROR_CHECK_EMAIL: '/result/error-check-email',
    ERROR_CHANGE_PASS: '/result/error-change-password',
    SUCCES_CHANGE_PASS: '/result/success-change-password',
    ERROR: '/result/error',
};
